[package]
name = "vectr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "4.0.1"
image = "0.23.6"
imageproc = "0.22.0"
rayon = "1.5.1"